parameters:
    darvin_image.size.describer.class: Darvin\ImageBundle\Size\SizeDescriber

services:
    _defaults:
        public: true

    darvin_image.size.describer:
        class:  "%darvin_image.size.describer.class%"
        public: false
        arguments:
            - "@liip_imagine.filter.configuration"
            - "@translator"
            - "%darvin_image.imagine.filter_sets%"
