parameters:
    darvin_image.archiver.zip.class:   Darvin\ImageBundle\Archive\ZipArchiver
    darvin_image.archiver.zip.tmp_dir: '%darvin_image.tmp_dir%/archives'

services:
    _defaults:
        public: true

    darvin_image.archiver.zip:
        class:  '%darvin_image.archiver.zip.class%'
        public: false
        arguments:
            - '@filesystem'
            - '@request_stack'
            - '%darvin_image.archive.filename_suffix%'
            - '%darvin_image.archiver.zip.tmp_dir%'
            - '%kernel.project_dir%/public/%darvin_image.upload_path%'
