darvin_image_archive_build:
    path:     /build
    defaults: { _controller: Darvin\ImageBundle\Controller\ArchiveController::buildAction }
    methods:  [ post ]

darvin_image_archive_download:
    path:         /download/{filename}
    defaults:     { _controller: Darvin\ImageBundle\Controller\ArchiveController::downloadAction }
    requirements: { filename: '\\w+%darvin_image.archive.filename_suffix%_\\d{4}-\\d{2}-\\d{2}_\\d{2}-\\d{2}.zip' }
    methods:      [ get ]
